### ISSUE TITLE
En aquest moment es pot exportar (obra civil), però seria interessant "importar" a l'eina.

### ISSUE THREAD

**Issue by agustim** [guifi/fiberfy-server#9]

**Comment by rgf1042** [comment]
Afegir només la part de l'API (si s'escau), debatre si és millor ferho a "client side" o "server side".

**Comment by rgf1042** [comment]
Server side a commit 1706231acb65f7fe2a41ba8ccbfe9ae45d6a8848

**Comment by rgf1042** [comment]
Aquí ja està resolt 8a0ca32d030c823aa5b8d1139af9f842feeda62d
